dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('df_user.urls')),
    url(r'^', include('df_goods.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),

]

df_cart/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add/$', views.add, name='add'),
    url(r'^del/$', views.del_cart, name='del_cart'),
]

df_user/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),

    url(r'^register_handle/', views.register_handle, name='register_handle'),
    url(r'^login_handle/', views.login_handle, name='login_handle'),


    url(r'^check_username/$', views.check_username, name='check_username'),
    url(r'^check_email/$', views.check_email, name='check_email'),

    url(r'^site/$', views.site, name='site'),
    url(r'^info/$', views.info, name='info'),
    url(r'^order/$', views.order, name='order'),
    url(r'^area_handle/$', views.area_handle, name='area_handle'),
    url(r'^change_site/(\d+)/$', views.change_site, name='change_site'),
    url(r'^edit_info/$', views.edit_info, name='edit_info'),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^send_captcha/$', views.send_captcha, name='send_captcha'),

    url(r'add_address/$', views.add_address, name="add_address"),
]

df_order/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

from base_manager import BaseManager
import hashlib
import datetime


class Order(models.Model):

    order_id = models.CharField(max_length=30, primary_key=True)
    user = models.ForeignKey("df_user.UserInfo")
    count = models.IntegerField()
    total = models.DecimalField(max_digits=5, decimal_places=2,verbose_name='实付')
    fare = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='运费')
    area = models.ForeignKey('df_user.AreaInfo', null=True)
    address = models.CharField(max_length=256)
    phone = models.CharField(max_length=11)
    receiver = models.CharField(max_length=20)
    ctime = models.DateTimeField(auto_now_add=True)
    order_status_choices = (
        (0, '未支付'),
        (1, '已付款'),
        (2, '已发货'),
        (3, '已收货'),
        (4, '已完成'),
    )
    status = models.SmallIntegerField(choices=order_status_choices)


    isDelete = models.BooleanField(default=False)

    objects = BaseManager()
    old_objects = models.Manager()

    def __init__(self, *args, **kwargs):

        uid = kwargs['user'].id if 'user' in kwargs else kwargs.get('user_id')

        kwargs['order_id'] = self.gen_order_id(uid)

        super(Order, self).__init__(*args, **kwargs)

    def gen_order_id(self, uid):
        m = hashlib.md5()
        m.update(str(uid).encode())
        ustr = m.hexdigest()[-7:-1]
        d = datetime.datetime.now()
        timestr = '%s%s%s%s%s%s%s' % (d.year, d.month, d.day, d.hour, d.minute, d.second, str(d.microsecond).rjust(6, '0'))
        return ''.join([timestr, ustr])

    class Meta:
        ordering = ['-ctime']

    def __str__(self):
        return self.order_id

class OrderDetail(models.Model):

    order = models.ForeignKey("Order")
    goods = models.ForeignKey("df_goods.GoodsInfo")
    count = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    unit = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)

    objects = BaseManager()
    old_objects = models.Manager()

    @property
    def total(self):
        return self.price*self.count

    def __str__(self):
        return "<%s-%s>" % (self.order, self.goods)

if __name__ == "__main__":
    Order().orderdetail_set

df_user/models.py
import hashlib

from django.db import models

# Create your models here.

def pwd_gen(pwd):
    s1 = hashlib.sha1()
    s1.update(pwd.encode())
    return s1.hexdigest()


class UserInfo(models.Model):
    uname = models.CharField(max_length=20, unique=True)
    _upwd = models.CharField(max_length=40)
    nikename = models.CharField(max_length=20, default='')
    uemail = models.EmailField(default='', unique=True)
    uphone = models.CharField(max_length=11, default='')
    verify_p = models.BooleanField(default=False)
    verify_e = models.BooleanField(default=False)
    default_addr = models.OneToOneField("AddressInfo", related_name='_user', null=True)

    def __str__(self):
        return self.uname

    @property
    def upwd(self):
        return self._upwd

    @upwd.setter
    def upwd(self, pwd):
        self._upwd = pwd_gen(pwd)

    def check_pwd(self, pwd):
        return self._upwd == pwd_gen(pwd)

class AddressInfo(models.Model):
    user = models.ForeignKey('UserInfo')
    receiver = models.CharField(max_length=25)
    # province = models.ForeignKey("AreaInfo", related_name='province')
    # city = models.ForeignKey("AreaInfo", related_name='city')
    area = models.ForeignKey("AreaInfo", related_name='address', null=True)

    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    postcode = models.CharField(max_length=6)

    def __str__(self):
        return "<%s-%s>" % (self.user, self.area.name)


class AreaInfo(models.Model):
    name = models.CharField(max_length=30)
    parea = models.ForeignKey('self', null=True, blank=True)

    def __str__(self):
        return self.name

df_user/views.py
import json
import re
import logging
from django.shortcuts import render, redirect, HttpResponse, resolve_url, get_object_or_404
from django.http import JsonResponse
from django.utils.http import urlunquote
from django.core.paginator import Paginator
from django.core.cache import cache
from . import models
from . import task
from df_order.models import Order
from .decorators import require_login
from df_goods.models import GoodsInfo
from df_cart.models import Cart

logger = logging.getLogger('django')
# Create your views here.


def register(request):
    """注册页面"""
    user_id = request.session.get('user_id')
    if user_id:
        return redirect('index')
    return render(request, 'df_user/register.html')


def register_handle(request):
    """注册处理"""
    user_id = request.session.get('user_id')
    if user_id:
        return redirect('index')
    # 接收用户数据
    user_name = request.POST.get('user_name')
    pwd = request.POST.get('pwd')
    cpwd = request.POST.get('cpwd')
    email = request.POST.get('email')

    # 判断两次密码
    if pwd != cpwd:
        return render(request, 'df_user/register.html')

    user_obj = models.UserInfo()
    user_obj.uname = user_name
    user_obj.upwd = pwd
    user_obj.uemail = email
    user_obj.save()

    request.session['user_id'] = user_obj.id
    request.session['user_name'] = user_obj.uname

    return redirect(resolve_url('info'))


def login(request):
    user_id = request.session.get('user_id')
    if user_id:
        return redirect('index')
    username = request.COOKIES.get('username', '')
    context = {
        'username': username
    }
    next_url = request.GET.get('next_url')
    if next_url:
        context['next_url'] = next_url

    return render(request, 'df_user/login.html', context)





def login_handle(request):
    print(request.get_full_path())

    user_id = request.session.get('user_id')
    if user_id:
        return redirect('index')

    username = request.POST.get('username')
    pwd = request.POST.get('pwd')

    user_li = models.UserInfo.objects.filter(uname=username)

    context = {
        'username': username
    }

    if not user_li or len(user_li) != 1:
        context['user_error'] = '用户名错误！'
        return render(request, 'df_user/login.html', context)

    if not user_li[0].check_pwd(pwd):
        context['pwd_error'] = '密码错误！'
        return render(request, 'df_user/login.html', context)

    user_obj = user_li[0]
    request.session['user_id'] = user_obj.id
    request.session['user_name'] = user_obj.uname

    # 获取
    next_url = request.GET.get('next_url')
    if next_url:
        next_url = urlunquote(next_url)
        response = redirect(next_url)
    else:
        response = redirect(resolve_url('info'))

    if request.POST.get('remember', False):
        response.set_cookie('username', user_obj.uname, max_age=60 * 60 * 24 * 7)
    else:
        response.delete_cookie('username')

    return response


@require_login
def logout(request):
    request.session.flush()
    return redirect('index')


def check_username(request):
    username = request.GET.get('username')
    count = models.UserInfo.objects.filter(uname=username).count()
    data = {
        'count': count,
        'status': 200
    }
    return HttpResponse(json.dumps(data))


def check_email(request):
    email = request.GET.get('email')
    count = models.UserInfo.objects.filter(uemail=email).count()
    data = {
        'count': count,
        'status': 200
    }
    return HttpResponse(json.dumps(data))


@require_login
def site(request):
    if request.method == 'POST':
        consignee = request.POST.get('consignee')
        address = request.POST.get('address')
        code = request.POST.get('code')
        phone = request.POST.get('phone')

        data = {
            'status': 200,
            'errors': []
        }

        if not consignee:
            data['status'] = 400
            data['errors'].append('收件人不能为空!')

        if not address:
            data['status'] = 400
            data['errors'].append('收件地址不能为空!')

        if not phone:
            data['status'] = 400
            data['errors'].append('收件手机不能为空!')

        if not data['errors']:
            user_obj = request.df_user

            user_obj.ushou = consignee
            user_obj.uaddress = address
            user_obj.uyoubian = code
            user_obj.uphone = phone
            user_obj.save()

    context = {
        'user': request.df_user,
        'page_name': 'site',
        'shen': models.AreaInfo.objects.filter(parea__isnull=True),

    }

    return render(request, 'df_user/user_center_site.html', context)


@require_login
def change_site(request, aid):
    addr_obj = get_object_or_404(models.AddressInfo, pk=aid)
    erros_msg = {}
    if request.method == 'POST':
        receiver = request.POST.get('receiver')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        aid = request.POST.get('aid')
        postcode = request.POST.get('postcode', None)

        if len(receiver) < 2:
            erros_msg['receiver'] = "收件人长度不能小于2个字符！"
        elif len(address) < 5:
            erros_msg['address'] = "收件详细地址长度不能小于5个字符！"
        elif not re.match(r'^1([358][0-9]|4[579]|66|7[0135678]|9[89])[0-9]{8}$', phone):
            erros_msg['phone'] = "手机号格式不正确！"
        elif postcode and not re.match(r'^[1-9][0-9]{5}$', postcode):
            erros_msg['postcode'] = "邮编格式不正确！"
        else:
            area_obj = get_object_or_404(models.AreaInfo, pk=aid)
            addr_obj.area = area_obj
            addr_obj.receiver = receiver
            addr_obj.address = address
            addr_obj.phone = phone
            addr_obj.save()
        if not erros_msg:
            next_url = request.GET.get('next_url')
            if next_url:
                return redirect(next_url)
            return redirect('site')

    context = {
        'addr': addr_obj,
        'error': erros_msg,
    }

    return render(request, 'df_user/user_center_edit.html', context)


@require_login
def info(request):

    record = request.COOKIES.get('record')

    if record:
        record_li = record.split(',')
        records_obj_q = GoodsInfo.objects.filter(pk__in=record_li)
        # 根据访问顺序对查询结果排序
        records_obj = []
        for i in [int(i) for i in record_li]:
            for g in records_obj_q:
                if i == g.id:
                    records_obj.append(g)
                    break
    else:
        records_obj = []

    context = {
        'user': request.df_user,
        'page_name': 'site',
        'records': records_obj
    }

    return render(request, 'df_user/user_center_info.html', context)


@require_login
def order(request):
    pid = request.GET.get('p', 1)

    pid = int(pid)

    orders = Order.objects.filter(user=request.df_user)

    p = Paginator(orders, 5)

    if pid > p.num_pages or pid < 1:
        pid = 1
    page = p.page(pid)
    if pid == p.num_pages:
        page.next = 0
    else:
        page.next = page.next_page_number()
    if pid == 1:
        page.prev = 0
    else:
        page.prev = page.previous_page_number()

    context = {
        'user': request.df_user,
        'page': page,
    }

    return render(request, 'df_user/user_center_order.html', context)


def area_handle(request):
    aid = request.GET.get('aid')
    area_obj = models.AreaInfo.objects.get(pk=aid)
    context = {
        'data': list(area_obj.areainfo_set.values()),
        'status': 200

    }
    return HttpResponse(json.dumps(context))


@require_login
def edit_info(request):
    msgs = []
    u_dic = {}
    if request.method == "POST":
        data = request.POST.get('data')
        user_obj = request.df_user
        if data:
            dic = json.loads(data)

            # 判断邮箱、手机号是否变更，如果变更把验证状态改为False
            if 'uemail' in dic and dic['uemail'] != user_obj.uemail:
                if re.match(r'\w@\w*\.\w', dic['uemail']):
                    user_obj.verify_e = False
                else:
                    dic.pop('uemail')
                    msgs.append('邮箱格式不正确！')

            if 'uphone' in dic and dic['uphone'] != user_obj.uphone:
                if re.match(r'^1([358][0-9]|4[579]|66|7[0135678]|9[89])[0-9]{8}$', dic['uphone']):
                    user_obj.verify_p = False
                else:
                    dic.pop('uphone')
                    msgs.append('手机号格式不正确！')

            for k, v in dic.items():
                if hasattr(user_obj, k) and getattr(user_obj, k) != v:
                    setattr(user_obj, k, v)
                    u_dic[k] = v

            user_obj.save()
        else:
            msgs.append("参数错误！")

        response = {
            'status': 400 if msgs else 200,
            'msg': msgs,
            'data': u_dic,
        }

        return JsonResponse(response)


@require_login
def verify(request):
    if request.method == 'GET':
        t = request.GET.get('t')
        if t:
            if t == 'p' and request.df_user.verify_p:
                return redirect('info')
            elif t == 'e' and request.df_user.verify_e:
                return redirect('info')
            context = {
                'page_name': '验证手机号' if t == 'p' else '验证邮箱',
                'user': request.df_user,
                't': t,
                'cart_count': Cart.objects.filter(user=request.df_user).count(),
            }
            return render(request, 'df_user/user_center_verify.html', context)

    elif request.method == 'POST':
        t = request.POST.get('t')
        if t == 'p':
            # 验证手机号
            code = request.POST.get('code')
            cache_code = cache.get(request.df_user.uphone)
            if cache_code and code.lower() == cache_code.lower():
                cache.delete(request.df_user.uphone)
                request.df_user.verify_p = True
                request.df_user.save()
                return redirect('info')
            else:
                context = {

templates/df_user/base_user.html
{% extends 'base_top.html' %}

{% load static %}


{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'info' %}" {% if request.resolver_match.url_name == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'order' %}" {% if request.resolver_match.url_name == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'site' %}" {% if request.resolver_match.url_name == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block right_content %}
        
        {% endblock %}

	
    </div>


{% endblock %}

templates/df_user/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    登陆
{% endblock %}

{% block body %}



	<div class="login_top clearfix">
		<a href="{% url 'index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'login_handle' %}{% if next_url %}?next_url={{ next_url }}{% endif %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" {% if username %}value="{{ username }}"{% else %}{% endif %}>
						<div class="user_error">用户名错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">用户错误错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/df_user/register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    注册
{% endblock %}

{% block head %}
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block body %}


	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="{% url 'index' %}"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'register_handle' %}" method="post" id="reg_form">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>


	{% endblock %}

templates/df_user/user_center_edit.html
{% extends 'df_user/base_user.html' %}
{% load static %}

{% load address_handle %}

{% block title %}
    收货地址
{% endblock %}

{% block right_content %}

    <div class="right_content clearfix">
        <h3 class="common_title2">
            {% if request.resolver_match.url_name == 'change_site' %}
                编辑地址
            {% else %}
                添加地址
            {% endif %}

        </h3>
        <div class="site_con">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form_group">
                    <label>收件人：</label>
                    <input type="text" name="receiver" value="{{ addr.receiver }}">
                    <p id="receiver_msg" style=" {% if not error.receiver %}display: none;{% endif %}color: red;">{{ error.receiver }}</p>
                </div>

                <div class="form_group form_group2 addr_area">
                    <label>选择区域：</label>
                    {% if request.resolver_match.url_name == 'change_site' %}
                        {% select_handle addr %}
                    {% else %}
                        <select name="" id="">
                            <option value="">---</option>
                            {% for province in provinces %}
                                <option value="{{ province.id }}">{{ province.name }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}


                </div>

                <div class="form_group form_group2">
                    <label>详细地址：</label>
                    <textarea class="site_area" name="address">{{ addr.address }}</textarea>
                    <p id="address_msg" style=" {% if not error.address %}display: none;{% endif %}color: red;">{{ error.address }}</p>
                </div>

                <div class="form_group">
                    <label>手机：</label>
                    <input type="text" name="phone" value="{{ addr.phone }}">
                    <p id="phone_msg" style=" {% if not error.phone %}display: none;{% endif %}color: red;">{{ error.phone }}</p>
                </div>
                <div class="form_group">
                    <label>邮编：</label>
                    <input type="text" name="postcode" value="{{ addr.postcode }}">
                    <p id="postcode_msg" style=" {% if not error.postcode %}display: none;{% endif %}color: red;">{{ error.postcode }}</p>
                </div>
                <input type="submit" name="" value="提交" class="info_submit">
                <p id="all_msg" style=" {% if not error.all %}display: none;{% endif %}color: red;">{{ error.all }}</p>
            </form>
        </div>
    </div>

    <script>
        $(function () {


            $('.addr_area').on('change', function (e) {
                if (e.target.tagName.toLowerCase() == 'select') {

                    var $this = $(e.target);
                    var aid = $this.val();
                    if (!aid) {
                        return
                    }
                    $.get({
                            url: "{% url 'area_handle' %}",
                            data: {'aid': aid},
                            dataType: 'JSON',
                            success: function (data) {

                                // 删除后面的select
                                $this.nextAll().remove();

                                if (data.data.length != 0) {
                                    var ele = '';
                                    ele += '<select><option value="">--选择--</option>';
                                    $.each(data.data, function (index, item) {
                                        ele += '<option value="' + item.id + '">' + item.name + '</option>'
                                    });
                                    ele += '</select>';

                                    $this.after(ele);
                                }


                            }
                        }
                    )
                }

            });

            $('input:submit').click(function () {
                var aid = $('select:last').val();
                if (!aid){
                    alert("请先选择地区！");
                    return false
                }

                var receiver = $('input[name="receiver"]').val();
                if (!receiver || receiver.length<2){
                    alert("请输入收件人！");
                    return false
                }

                var phone = $('input[name="phone"]').val();
                if (!phone || phone.length != 11){
                    alert("请输入收件人手机号！");
                    return false
                }

                var addr = $('textarea[name="address"]').val();
                if (!addr || addr.length<5 ){
                    alert("请输入收件人地址！");
                    return false
                }
                $(this).attr('name', 'aid');
                $(this).val(aid);
            })

        })

    </script>
{% endblock %}

templates/df_user/user_center_order.html
{% extends 'df_user/base_user.html' %}
{% load order_page_handler %}

{% block title %}
    我的订单
{% endblock %}


{% block right_content %}


    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>

        {% if page.paginator.count == 0 %}
            <div style="text-align: center">您还没有订单！ <a href="{% url 'index' %}">去主页</a></div>
        {% else %}
            {% for order in page.object_list %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.ctime|date:"Y-m-d H:i:s" }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress">状态：{{ order.get_status_display }}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for detail in order.orderdetail_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><a href="{% url 'detail' detail.id %}"><img src="/static/{{ detail.goods.gpic }}"></a></li>
                                    <li class="col02"><a href="{% url 'detail' detail.id %}">{{ detail.goods.gtitle }}</a>

                                        <em>{{ detail.price }}元/{{ detail.unit }}</em></li>
                                    <li class="col03">{{ detail.count }}</li>
                                    <li class="col04">{{ detail.total }}元</li>
                                </ul>
                            {% endfor %}

                        </td>
                        <td width="15%">
                            {{ order.total }}元
                            <br>
                            (含运费：{{ order.fare }}元)
                        </td>
                        <td width="15%">{{ order.get_status_display }}</td>
                        <td width="15%"><a href="#" class="oper_btn">
                            {% if order.status == 0 %}
                                去付款
                            {% else %}
                                查物流
                            {% endif %}
                        </a></td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
        {% endif %}


        {% order_page_handler page %}

    </div>



{% endblock %}

templates/df_user/user_center_site.html
{% extends 'df_user/base_user.html' %}
{% load static %}

{% load address_handle %}

{% block title %}
    收货地址
{% endblock %}

{% block right_content %}




    <div class="right_content clearfix">
        <h3 class="common_title2">收货地址</h3>
        <div class="site_con">
            <dl>
                {% if user.default_addr %}
                    <dd>
                        <label>
                        <input type="radio" name="addr_id" checked="" value="{{ user.default_addr.id }}">
                        &nbsp;{% address_handle user.default_addr %}(默认地址)
                        </label>
                        <a href="{% url 'change_site' user.default_addr.id %}">编辑</a>
                    </dd>
                {% endif %}

                {% for addr in user.addressinfo_set.all %}
                    {% if user.default_addr.id != addr.id %}
                        <dd>
                            <label>
                            <input type="radio" name="addr_id" value="{{ addr.id }}">
                            &nbsp;{% address_handle addr %}
                            </label>
                        <a href="{% url 'change_site' addr.id %}">编辑</a>
                        </dd>
                    {% endif %}
                {% endfor %}
            <a href="{% url 'add_address' %}" style="text-align: center; display: block;">点击这里添加地址！</a>

            </dl>

        </div>
    </div>


{% endblock %}